---
title: "MARC Early Summer Reflection"
author: "Jacob M. Green"
date: "6/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### We want to know about you

**Tell a story about you:** Be specific. Take your belief out of the ether and ground it in the events that have shaped your core values. Consider moments when belief was formed or tested or changed. Think of your own experience, work, and family, and tell of the things you know that no one else does. Your story need not be heart-warming or gut-wrenching—it can even be funny—but it should be real. Make sure your story ties to the essence of your daily life philosophy and the shaping of your beliefs.

**Be brief:** Your statement should be between 500 and 600 words. That’s about three minutes when read aloud at your natural pace.

**Name your belief:** If you can’t name it in a sentence or two, your essay might not be about belief. Also, rather than writing a list, consider focusing on one core belief.

**Be positive:** Write about what you do believe, not what you don’t believe. Avoid statements of religious dogma, preaching, or editorializing.

**Be personal:** Make your essay about you; speak in the first person. Avoid speaking in the editorial “we.” Tell a story from your own life; this is not an opinion piece about social ideals. Write in words and phrases that are comfortable for you to speak. We recommend you read your essay aloud to yourself several times, and each time edit it and simplify it until you find the words, tone, and story that truly echo your belief and the way you speak.