---
title: "MARC Creating Abstracts Session"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Leader Name: Jacob Green | Course: Planning form temp     |
|--------------------------|--------------------------------|
| Date created:6/16/2020   | Date implemented:6/18/2020     |
| Week in course:2         | Resources: Abstract Folder     |

## Step 1: Meet with coordinators and discuss the following:
Useful resource; **"Identifying the Difficulties with Difficult Ideas"**

1. List the most important concepts and skill introduced in this topic
    a. Concepts
        * Abstracts have multiple uses
        * Abstracts take many different forms
        * There is no single format for writing abstract, varies by discipline
    b. Skills
        * Identifying the components of an abstract
        * Communicating your research in writing
        * Drafting without organization (word vomit)
        * Self review vs. mentor review

2. Which concepts and skills can be the most challenging for researchers this week? Why?

## Step 2: Plan your session based on who is attending in the lecture and meeting with the instructor
When planning your sessions remember to stay flexible with the actual implementation of your session plan. Trainees may come prepared with their own questions and agenda. Stay open to their requests. Useful handouts; **Bloom's Taxonomy, Learning Outcome ABC's, S.M.A.R.T, Strategy Du Jour.**

1. **Session Learning Objectives**
Describe what you would like to see your trainees be able to do by the end of your sessions? Use the list of concepts and skills you identified in Step #1. 

I would like all trainees to be able to define and identify the different uses and sections of on abstract. 

1) I would like returning trainees to articulate a motivation and methods for their project

2) I would like new trainnes to articulate a motivation for their research idea or question. 

Both can articulate more but with limited time I am not expecting them to even structure these ideas. The goal is to spend 15 minutes on word vomitting imotivation for research.

2. **Check-in**
Allow for a 10-20 minute period where trainees are able to communicate with coordinators and each other about the weeks goals, trials, and tribulations.

Today we are discussing abstracts and we have two options. Option 1: We will discuss abstracts and what you all know about them, define the use and structure of abstracts, and have some time to develop abstracts. Option 2: At 6-7 pm there is an event "Writing a Compelling Abstract" hosted by ABRCMS & ASM here: https://www.pathlms.com/asm/courses/15609/sections/21487. If you would like to continue to write and have me available from 6 - 630 pm I am more than happy to stay here an answer question. I also think it would be beneficial to attend the abstract session for ASM as this is the organization we will be sending abstracts to for the conference. 

I also want you to know that alongside ABRCMS there are other organizations. SACNAS, the Society for the Advancement of Native Americans and Chicanos in Science, is an organization that I have been apart of since 2015 and is the first place that I presented my research. They also have a fall 202 conference in Long Beach, which also might be reworked due to COVID. Still their deadline for presenting a poster or oral presentation would be July 15th. 

Share reworked SMART goals.

3. **Warm-up**
Describe a 10-15 minute opportunity that will help trainees to organize, prioritize, define, identify, label, list, record, or review, ideas.

We are going to use what is called a KWL table. Anyone familiar with this strategy? It is a table. KWL stands for know, want to know, and learn. We will spend the next 5 minutes writing what you know and want to know about abstracts. At the end of the session we will take time to reflect on what we can move into the learn category.

6-10 minutes discussing those ideas.

4. **Most of the session time**
Describe how you will utilize the meeting activity (50-60 minutes) to help trainees achieve the learning objectives you have developed.

1) Review abstracts 

2) Word vomit research motivation and methodology

5. **Wrap-up**
Describe a 10-15 minute closing opportunity that will help trainees summarize their work in today's session. 

Reflect on what to move from the want to know category to the learn category or add things that you learned. What else do you still want to know or feel like we have not addressed?

## Step 3: Reflect on this week's session
Once you have hosted the session and completed the reflection share your completed session plan with your coordinators and review all of the activites from that week.

**1. What worked in the session? What was successful?**

**2. What did trainees learn? How do you know?**

**3. What would you change about your session today?**

**4. What specific content areas and study strategies did you recommend that trainees pursue before next week's sessions?**

**5. What are you considering as good use of next week's session?**

