---
title: "MARC Succeeding in Research Session"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Leader Name: Jacob Green | Course: Succeeding in Research |
|--------------------------|--------------------------------|
| Date created:6/8/2020    | Date implemented:6/11/2020     |
| Week in course:1         | Resources:                     |

## Step 1: Meet with coordinators and discuss the following:
Useful resource; **"Identifying the Difficulties with Difficult Ideas"**

1. List the most important concepts and skills introduced in this topic
    a. Concepts
        * Why use the research planning guide or finding research guide?
        * How to define your why, which guides your what.
        * What are SMART goals?
        * What are reasonable summer research goals?
    b. Skills
        * Articulating why you are doing research and pursuing this path to higher education
        * Identifying goals for summer research
        * Advocating for yourself through research projects
        * Developing strategies to be organized and productive
        
2. Which concepts and skills can be the most challenging for researchers this week? Why?

## Step 2: Plan your session based on who is attending in the lecture and meeting with the instructor
When planning your sessions remember to stay flexible with the actual implementation of your session plan. Trainees may come prepared with their own questions and agenda. Stay open to their requests. Useful handouts; **Bloom's Taxonomy, Learning Outcome ABC's, S.M.A.R.T, Strategy Du Jour.**

1. **Session Learning Objectives**
Describe what you would like to see your trainees be able to do by the end of your sessions? Use the list of concepts and skills you identified in Step #1. 

I would like to see trainees define 3 goals for their summer research experiences that are SMART. I would also like to hear how they plan to hold themselves and their advisors accountable through developing the finding research guide or research planning guide. I would like to hear how they will organize their work and ways that they are finding to be productive or other ways that they might have to develop to be productive.

2. **Check-in**
Allow for a 10-20 minute period where trainees are able to communicate with coordinators and each other about the weeks goals, trials, and tribulations.

I want to talk about the elephant in the room. We the MARC community are grounded in the priciples of maximizing accessing to research careers for URM students. That has been our goal from day one. The events such as the death of george ffloyd, ahmaud arbury, breonna taylor and many other reminds us that there are societal hurdles our students face when they are outside of school. Also, if we listen to the POC in academia we find that their path is similarly laden with racial bias, profiling, a lack of support, and in many cases outright distain. 

COVID-19 and valid and ongoing protests in support of BLM have created difficult circumstances and conversations. I do not want to shy away from those coversations. I would like you all to feel comfortable in this community sharing your thoughts, concerns, and wants. That is to say this is a place were we respect the thoughts and ideas of other fully. 

Questions: What is one thing that you are excited or confident about? What is one thing that you are curious about? What is one thing that you are confused about? (5 minutes to write and think & 15 minutes to share)

3. **Warm-up**
Describe a 10-15 minute opportunity that will help trainees to organize, prioritize, define, identify, label, list, record, or review, ideas.

List 3 research goals for this summer. 6 minutes to develop, 8 minutes to discuss

4. **Most of the session time**
Describe how you will utilize the meeting activity (50-60 minutes) to help trainees achieve the learning objectives you have developed. 

Start by having a disucssion around the Planning guides, SMART goals, and what are reasonable summer research goals. Develop a question for each. 

#### Planning guides

Activity: Take 10 minutes and read through the finding research guide or the research planning guide. 

Questions: Where can I be more specific? Will this be helpful?

#### SMART goals

Discussion: What are SMART goals? If trainees understand an aspect of a smart goal allow them to explain and expand if need be.

1. Specific
Your goal should be clear and specific, otherwise you won't be able to focus your efforts or feel truly motivated to achieve it. When drafting your goal, try to answer the five "W" questions:

What do I want to accomplish?
Why is this goal important?
Who is involved?
Where is it located?
Which resources or limits are involved?
Example
Imagine that you are currently a marketing executive, and you'd like to become head of marketing. A specific goal could be, "I want to gain the skills and experience necessary to become head of marketing within my organization, so that I can build my career and lead a successful team."

2. Measurable
It's important to have measurable goals, so that you can track your progress and stay motivated. Assessing progress helps you to stay focused, meet your deadlines, and feel the excitement of getting closer to achieving your goal.

A measurable goal should address questions such as:

How much?
How many?
How will I know when it is accomplished?
Example
You might measure your goal of acquiring the skills to become head of marketing by determining that you will have completed the necessary training courses and gained the relevant experience within five years' time.

3. Achievable
Your goal also needs to be realistic and attainable to be successful. In other words, it should stretch your abilities but still remain possible. When you set an achievable goal, you may be able to identify previously overlooked opportunities or resources that can bring you closer to it.

An achievable goal will usually answer questions such as:

How can I accomplish this goal?
How realistic is the goal, based on other constraints, such as financial factors?

Example

You might need to ask yourself whether developing the skills required to become head of marketing is realistic, based on your existing experience and qualifications. For example, do you have the time to complete the required training effectively? Are the necessary resources available to you? Can you afford to do it?

Tip:
Beware setting goals that someone else has power over. For example, "Get that promotion!" depends on who else applies, and on the recruiter's decision. But "Get the experience and training that I need to be considered for that promotion" is entirely down to you.

4. Relevant
This step is about ensuring that your goal matters to you, and that it also aligns with other relevant goals. We all need support and assistance in achieving our goals, but it's important to retain control over them. So, make sure that your plans drive everyone forward, but that you're still responsible for achieving your own goal.

A relevant goal can answer "yes" to these questions:

Does this seem worthwhile?
Is this the right time?
Does this match our other efforts/needs?
Am I the right person to reach this goal?
Is it applicable in the current socio-economic environment?

Example

You might want to gain the skills to become head of marketing within your organization, but is it the right time to undertake the required training, or work toward additional qualifications? Are you sure that you're the right person for the head of marketing role? Have you considered your spouse's goals? For example, if you want to start a family, would completing training in your free time make this more difficult?

5. Time-bound
Every goal needs a target date, so that you have a deadline to focus on and something to work toward. This part of the SMART goal criteria helps to prevent everyday tasks from taking priority over your longer-term goals.

A time-bound goal will usually answer these questions:

When?
What can I do six months from now?
What can I do six weeks from now?
What can I do today?

Example
Gaining the skills to become head of marketing may require additional training or experience , as we mentioned earlier. How long will it take you to acquire these skills? Do you need further training, so that you're eligible for certain exams or qualifications? It's important to give yourself a realistic time frame for accomplishing the smaller goals that are necessary to achieving your final objective.

Activity:

1) Take each goal identified in the warm-up and turn it into a smart goal. 

2) What are other goals you may think of?

3) How might these inform your planning/finding guide?

5. **Wrap-up**
Describe a 10-15 minute closing opportunity that will help trainees summarize their work in today's session. 

Question: What are you confused, confident, or curious about?

**Reminder** 
* Complete the Early Summer Reflection by next Thursday.
* Watch [Know your why](https://www.youtube.com/watch?v=1ytFB8TrkTo)
* Finding research or Research planning guide is due August 1st

## Step 3: Reflect on this week's session
Once you have hosted the session and completed the reflection share your completed session plan with your coordinators and review all of the activites from that week.

**1. What worked in the session? What was successful?**

**2. What did trainees learn? How do you know?**

**3. What would you change about your session today?**

**4. What specific content areas and study strategies did you recommend that trainees pursue before next week's sessions?**

**5. What are you considering as good use of next week's session?**