---
title: "MARC Coding Necessities"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Leader Name: Jacob Green | Course: Planning form temp                      |
|--------------------------|-------------------------------------------------|
| Date created:7/14/2020   | Date implemented:7/16/2020                      | 
| Week in course:6         | Resources:BVCN, Happy Belly Bioinformatics, PCFB|

## Step 1: Meet with coordinators and discuss the following:
Useful resource; **"Identifying the Difficulties with Difficult Ideas"**

1. List the most important concepts and skill introduced in this topic
    a. Concepts
        * Unix file-structure
        * Absolute vs. Relative Paths
        * Working with files and directories

    b. Skills
        * Running commands
        * Building comfortability with the command-line
        * Copying and moving files
        * Editing files

2. Which concepts and skills can be the most challenging for researchers this week? Why?

Unix-file structure is a system that we work in through a GUI. Taking the command-line approach to the UNIX system is disorienting and can take sometime getting used to. By far the skill I still lose is my comfortability with the command-line. If I stay away for too long I get less comfortable.

## Step 2: Plan your session based on who is attending in the lecture and meeting with the instructor
When planning your sessions remember to stay flexible with the actual implementation of your session plan. Trainees may come prepared with their own questions and agenda. Stay open to their requests. Useful handouts; **Bloom's Taxonomy, Learning Outcome ABC's, S.M.A.R.T, Strategy Du Jour.**

1. **Session Learning Objectives**
Describe what you would like to see your trainees be able to do by the end of your sessions? Use the list of concepts and skills you identified in Step #1. 

I would like to see my trainees make their own directory, create a file, write a file, save the file, make a copy of that file, and edit the copy.

2. **Check-in**
Allow for a 10-20 minute period where trainees are able to communicate with coordinators and each other about the weeks goals, trials, and tribulations.

1) Questions: How are you doing this week? 

2) Share accomplishments and concerns

3) Questions about the professional development portion

4) Midsummer Reflection document is up and ready to go

3. **Warm-up**
Describe a 10-15 minute opportunity that will help trainees to organize, prioritize, define, identify, label, list, record, or review, ideas.

Getting everyone to the "getting started" portion of Happy Belly Bioinformatics. From here we will get people into the BInder so we have a common environment to work from.

4. **Most of the session time**
Describe how you will utilize the meeting activity (50-60 minutes) to help trainees achieve the learning objectives you have developed.

We will walk through lesson 1 and 2 of the Happy Belly Bioinformatics Unix page. I am following the lead of the BVCN coordinator Ben Tully.

5. **Wrap-up**
Describe a 10-15 minute closing opportunity that will help trainees summarize their work in today's session. 

What was the easiest concept today?
What was the most difficult concept?
Access your own terminal and contact me if you need help.

## Step 3: Reflect on this week's session
Once you have hosted the session and completed the reflection share your completed session plan with your coordinators and review all of the activites from that week.

**1. What worked in the session? What was successful?**

The check-in for the session went very well. In weeks previous I left the check in fairly open ended and it made the discussion less focused and less constructive. By asking a series of question it allowed for us to discuss more specific concerns. Also, I felt that the coding excercise went fairly well, especially considering it was my first time walking a group of people through these excercises. We left time for questions and active discussion in specific areas that slowed us down, but in a way that increased engagement and showcased trainee knowledge and experiences in this subject.

**2. What did trainees learn? How do you know?**

Trainees learned the following

| Term     | What it is          |
|:----------:|------------------|
| **`path`** | the address system the computer uses to keep track of files and directories |
| **`root`** | where the address system of the computer starts, **`/`** |
| **`home`** | where the current user's location starts, **`~/`**|
| **`absolute path`** | an address that starts from a specified location, i.e. root, or home |
| **`relative path`** | an address that starts from wherever we are |
| **`tab-completion`** | our best friend |


<h4><i>Commands introduced:</i></h4>

|Command     |Function          |
|:----------:|------------------|
|**`date`**| prints out information about the current date and time |
|**`head`**| prints out the first lines of a file |
|**`pwd`**       |prints out where we are in the computer (**p**rint **w**orking **d**irectory)|
|**`ls`**        |lists contents of a directory (**l**i**s**t)|
|**`cd`**| **c**hange **d**irectories |


<h4><i>Special characters introduced:</i></h4>

|Characters     | Meaning          |
|:----------:|------------------|
| **`/`** | the computer's root location |
| **`~/`** | the user's home location |
| **`../`** |specifies a directory one level "above" the current working directory|


**3. What would you change about your session today?**

There is not much I would change. I was ambitious in thinking we would get through 2 examples. I am still feeling ambitious in thinking we will get through 2 in the next lesson. This would leave some session open. I am going to have to balance what we can get to. The bioinformatics stuff might have to be another session in the week added to the last two weeks.

**4. What specific content areas and study strategies did you recommend that trainees pursue before next week's sessions?**

I recommended that they attempt to download a terminal program (if necessary) and get familiar with the commands provided in the first lesson.

**5. What are you considering as good use of next week's session?**

Next weeks session we will work lesson 2 (working with files and directories) and lesson 3 (Redirectors and wildcards). If we can work through those we may be able to touch of the six glorious commands. I will also be assigning 3 excercises for them to compelte between the two sessions.

